### ISSUE TITLE
 Class 'Gstt\Achievements\AchievementsServiceProvider' not found

### ISSUE THREAD

**Issue by orlyapps** [gstt/laravel-achievements#10]
Hi,

when i run composer update i got the following error:

```
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Gstt\Achievements\AchievementsServiceProvider' not found

Script php artisan optimize handling the post-update-cmd event returned with error code 1
```

composer.json
...
"gstt/laravel-achievements": "^0.0.3",
...

config/app.php
...
Gstt\Achievements\AchievementsServiceProvider::class,
...

Laravel Framework 5.4.15

Looks like php artisan optimize crashed

**Comment by HDVinnie** [comment]
Make sure that you have "gstt/laravel-achievements": "^1.0" in the require section of your composer.json. Also, if you don't automatically download the latest version, try adding the "minimum-stability" : "RC", setting to the composer.json file.

**Comment by gabriel-simonetti** [comment]
@HDVinnie had the same issue on #6.

Make sure that you have `"gstt/laravel-achievements": "^1.0"` in the `require` section of your `composer.json`. Also, if you don't automatically download the latest version, try adding the `"minimum-stability" : "RC",` setting to the composer.json file.

For comparison, your `composer.json` file should look more or less [like this](https://github.com/gabriel-simonetti/laravel-achievements-example/blob/master/composer.json).

If you've done all that and it still shows the same error, try running `composer dump-autoload`.

**Comment by gabriel-simonetti** [comment]
@orlyapps I'm marking this is as solved. Please let me know if you're still experiencing this issue!
