### ISSUE TITLE
uuid on progress_details table

### ISSUE THREAD

**Issue by highnoon112** [gstt/laravel-achievements#16]
Hi

Im trying to understand why the id of table achievement_progress uses a unique identifier:

Uuid::uuid4()->toString();

Wouldnt a regular incremented integer suffice?

Thanks

**Comment by gabriel-simonetti** [comment]
Hi!

A regular incremented integer would indeed suffice, but choosing uuid was a design decision in order to make the implementation similar to [Laravel Notifications](https://laravel.com/docs/5.4/notifications).

**Comment by highnoon112** [comment]
Thanks Gabriel-simonetti!

I guess it makes sense when achievements/notifications are removed from the folder while simultaneously updating the database. Eventually regular incremented integers from the progress table might mistakenly point to to the new achievement id in the details table of which the id formerly belonged to the removed achievement. 

Great work. Thanks ever so much!
