### ISSUE TITLE
Multilanguage Achiefment

### ISSUE THREAD

**Issue by martdegraaf** [gstt/laravel-achievements#18]
How do i make the achiefment multilanguage? I see the achiefment as somethign that is saved in the database, but how do i translate this achiefment?

**Comment by gabriel-simonetti** [comment]
The package itself has no translation feature, but you could accomplish that by using the [Localization](https://laravel.com/docs/5.4/localization) feature in Laravel.

This is how I would do this (I am using Brazilian Portuguese as an example):

### 1) Store the Achievement name and description as translation short keys.

```php
<?php

namespace App\Achievements;

use Gstt\Achievements\Achievement;

class UserMadeAPost extends Achievement
{
    /*
     * The achievement name
     */
    public $name = 'achievement.user_made_a_post.name';

    /*
     * A small description for the achievement
     */
    public $description = 'achievement.user_made_a_post.description';
}
```

### 2) Create translation files:

```
/resources
    /lang
        /en
            achievements.php
        /pt-br
            achievements.php
```

```php
<?php

// resources/lang/en/achievements.php

return [
    'user_made_a_post.name' => 'Post Created',
    'user_made_a_post.description' => 'You have created your first post'
];
```

```php
<?php

// resources/lang/pt-br/achievements.php

return [
    'user_made_a_post.name' => 'Post Criado',
    'user_made_a_post.description' => 'Você criou o seu primeiro post'
];
```

### 3) Call the Translation feature whenever you want to display the data

```
// resources/views/achievements/list.blade.php
@foreach($achievements as $item)
    <tr>
        <td>{{ __($item->details->name) }}</td>
        <td>{{ __($item->details->description) }}</td>
    </tr>
@endforeach
```

If you need help on how to display the Achievements on template, please check the [example package](https://github.com/gabriel-simonetti/laravel-achievements-example) I have created.

**Comment by martdegraaf** [comment]
That makes sense, Thank you very much.

**Comment by gabriel-simonetti** [comment]
You're welcome! Thanks for using the package.
