### ISSUE TITLE
getOrCreateProgressForAchiever ignores achiever?

### ISSUE THREAD

**Issue by orlyapps** [gstt/laravel-achievements#2]
Problem:
Only for user A a database record was created in the "achievement_progress" table.

$progress = AchievementProgress::where('achiever_type', $className)
           ->where('achievement_id', $achievementId)
           ->where('achiever_id', $achiever->id) // i think you forgot this line?
           ->first();

**Comment by gabriel-simonetti** [comment]
Absolutely! Thanks for noticing. Fixed on 0.0.3.
