### ISSUE TITLE
[Question] Cron Job for achivement progress?

### ISSUE THREAD

**Issue by byjokese** [gstt/laravel-achievements#20]
Several Achievements use some DB data for their progress, how can I update the point progress of the achievements?

I was thinking on a cron job every X time that checks the DB and sets the progress. How can I implement something like that in Laravel?

Thank you, great job!

**Comment by gabriel-simonetti** [comment]
Hi Ivan! The documentation has a clear explanation on [how to add, remove or reset the progress on a specific achievement](https://github.com/gstt/laravel-achievements#-adding-progress). Check it out!

If you need details on how to run Laravel code on a cronjob, I suggest you create an Artisan command that does that. You can see details on [how to create Artisan commands](https://laravel.com/docs/5.6/artisan) or [how to schedule Artisan commands](https://laravel.com/docs/5.6/scheduling#schedule-frequency-options).

**Comment by byjokese** [comment]
Good, will give it a try with the artisan commands.

**Comment by byjokese** [comment]
One further question, what happens if I say to unlock a previously unlocked achievement? does it change the timestamps?

**Comment by gabriel-simonetti** [comment]
No, it doesn't. Any attempts to unlock a previously unlocked achievement are simply ignored.

**Comment by byjokese** [comment]
Perfect, that's what I wanted to know.
