### ISSUE TITLE
[REQUEST] Improve returned data

### ISSUE THREAD

**Issue by byjokese** [gstt/laravel-achievements#21]
When doing a query for user achievements and unlocked ones, the returned data is not pretty optimized. (Personal point of view).

Example of `$user->unlockedAchievements()->all()`:

`Array ( [0] => Gstt\Achievements\Model\AchievementProgress Object ( [incrementing] => [table:protected] => achievement_progress [guarded:protected] => Array ( ) [casts:protected] => Array ( [unlocked_at] => datetime ) [connection:protected] => mysql [primaryKey:protected] => id [keyType:protected] => int [with:protected] => Array ( ) [withCount:protected] => Array ( ) [perPage:protected] => 15 [exists] => 1 [wasRecentlyCreated] => [attributes:protected] => Array ( [id] => 77352394-32ec-4122-a970-dc2614ae51f6 [achievement_id] => 4 [achiever_id] => 1 [achiever_type] => App\User [points] => 0 [unlocked_at] => 2018-02-21 19:02:54 [created_at] => 2018-03-02 13:32:00 [updated_at] => 2018-03-02 13:32:00 ) [original:protected] => Array ( [id] => 77352394-32ec-4122-a970-dc2614ae51f6 [achievement_id] => 4 [achiever_id] => 1 [achiever_type] => App\User [points] => 0 [unlocked_at] => 2018-02-21 19:02:54 [created_at] => 2018-03-02 13:32:00 [updated_at] => 2018-03-02 13:32:00 ) [changes:protected] => Array ( ) [dates:protected] => Array ( ) [dateFormat:protected] => [appends:protected] => Array ( ) [dispatchesEvents:protected] => Array ( ) [observables:protected] => Array ( ) [relations:protected] => Array ( ) [touches:protected] => Array ( ) [timestamps] => 1 [hidden:protected] => Array ( ) [visible:protected] => Array ( ) [fillable:protected] => Array ( ) ) [1] => Gstt\Achievements\Model\AchievementProgress Object ( [incrementing] => [table:protected] => achievement_progress [guarded:protected] => Array ( ) [casts:protected] => Array ( [unlocked_at] => datetime ) [connection:protected] => mysql [primaryKey:protected] => id [keyType:protected] => int [with:protected] => Array ( ) [withCount:protected] => Array ( ) [perPage:protected] => 15 [exists] => 1 [wasRecentlyCreated] => [attributes:protected] => Array ( [id] => 95d4e3c1-64f2-4649-be50-fa81d90e98fc [achievement_id] => 1 [achiever_id] => 1 [achiever_type] => App\User [points] => 1 [unlocked_at] => 2018-02-21 19:02:54 [created_at] => 2018-02-21 19:02:54 [updated_at] => 2018-02-21 19:02:54 ) [original:protected] => Array ( [id] => 95d4e3c1-64f2-4649-be50-fa81d90e98fc [achievement_id] => 1 [achiever_id] => 1 [achiever_type] => App\User [points] => 1 [unlocked_at] => 2018-02-21 19:02:54 [created_at] => 2018-02-21 19:02:54 [updated_at] => 2018-02-21 19:02:54 ) [changes:protected] => Array ( ) [dates:protected] => Array ( ) [dateFormat:protected] => [appends:protected] => Array ( ) [dispatchesEvents:protected] => Array ( ) [observables:protected] => Array ( ) [relations:protected] => Array ( ) [touches:protected] => Array ( ) [timestamps] => 1 [hidden:protected] => Array ( ) [visible:protected] => Array ( ) [fillable:protected] => Array ( ) ) ) `

Is really all that data necessary for just 2 achievements? Could be refactored on simpler and more usefull way?

**Comment by gabriel-simonetti** [comment]
It's the default return values for Laravel relationships. `$user->achievements()` returns an instance of [MorphMany](https://laravel.com/api/5.6/Illuminate/Database/Eloquent/Relations/MorphMany.html) (a type of relationship) and calling `->all()` on that will return a [Collection ](https://laravel.com/api/5.6/Illuminate/Database/Eloquent/Collection.html)of [Models](https://laravel.com/api/5.6/Illuminate/Database/Eloquent/Model.html).

**Comment by byjokese** [comment]
Okay.

**Comment by byjokese** [comment]
Sorry for making lots of questions, but I really should implement my own system. How can I list all achievements? There are user operations, but not seeing nothing like: `Achivement::All();`. How can I do it?

**Comment by byjokese** [comment]
@gabriel-simonetti  can you help with that?

**Comment by byjokese** [comment]
No one? I haven't seen that feature, I guess I will have to assign all achievements to one user and fetch them from it.

**Comment by gabriel-simonetti** [comment]
Hy @byjokese, I'm sorry for the late response.

`AchievementDetails::all()` shoulf return the complete list of Achievements already synchronized to the database.
