### ISSUE TITLE
  Command "make:achievement" is not defined.

### ISSUE THREAD

**Issue by AqibTeam** [gstt/laravel-achievements#25]
Hi, I have recently installed the package, I when I tried to run the following command, the terminal return mi the next error:
domain@hl361:~/www$ php artisan make:achievement UserMadeAPost
  Command "make:achievement" is not defined.
  Did you mean one of these?
      make:auth
      make:chart
      make:command
      make:controller
      make:event
      make:exception
      make:factory
      make:job
      make:listener
      make:mail
      make:middleware
      make:migration
      make:model
      make:notification
      make:policy
      make:provider
      make:request
      make:resource
      make:rule
      make:seeder
      make:test

**Comment by gabriel-simonetti** [comment]
HI! I'm sorry for the last response.

Have you added the ServiceProvider to the providers section of your config.php file as described on the readme file?
