### ISSUE TITLE
Multiple Models as Achiever

### ISSUE THREAD

**Issue by droplister** [gstt/laravel-achievements#31]
I have two models that I'd like to earn achievements on, is that possible? I'm getting unexpected behavior.

**ModelOne**

```
use Gstt\Achievements\Achiever;
use Illuminate\Database\Eloquent\Model;

class ModelOne extends Model
{
    use Achiever;
}
```

**ModelTwo**

```
use Gstt\Achievements\Achiever;
use Illuminate\Database\Eloquent\Model;

class ModelTwo extends Model
{
    use Achiever;
}
```

Achievements are working as expected for ModelOne, but ModelTwo is not. This, for example, is getting wrongly saved as being ModelOne...

```
$model = ModelTwo::first();
$model->unlockIfLocked(new ThisAchievement());
```

And the achievements relationship is screwy, as well. ` App\ModelTwo::has('achievements')->first()` does this...

```

Illuminate/Database/QueryException with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'achiever_id' cannot be null (SQL: insert into `achievement_progress` (`achievement_id`, `achiever_id`, `achiever_type`, `points`, `id`, `updated_at`, `created_at`) values (1, , App/ModelTwo, 0, d319c898-482c-4833-bc3d-a2c588ba1545, 2018-08-23 12:13:28, 2018-08-23 12:13:28))'
```

It's possible that it's related to my custom trait that I made:

```
namespace App\Traits;

use Gstt\Achievements\Achievement;

trait Achievable
{
    /**
     * Unlock If Locked
     * 
     * @param Achievement $achievement
     * @return void
     */
    public function unlockIfLocked(Achievement $achievement)
    {
        if(! $this->hasUnlocked($achievement))
        {
            $this->unlock($achievement);
        }
    }
}
```

**Comment by gabriel-simonetti** [comment]
Hi Dan!

By taking a look at what you posted, it seems that the issue is related on how ModelTwo is saved to the database. When it tried to save an instance of an achievement being unlocked on ModelTwo, it failed because it could not identify the primary column for that instance.

Could you please answer the following questions?

- What data is being saved in the `ModelTwo` instance?
- Do the `ModelTwo` class has an `id` column?
- Are you calling `unlockIfLocked` to an instance that has not yet being saved to the database?

**Comment by droplister** [comment]
Actual Models:
https://github.com/droplister/bitcorns.com/blob/master/app/Farm.php
https://github.com/droplister/bitcorns.com/blob/master/app/Token.php

Example of where it fails:
https://github.com/droplister/bitcorns.com/blob/master/app/Listeners/MuseumListener.php

Do you have issues with has and withCount?

**Comment by droplister** [comment]
Both of these models use `$table->increments('id')`. Hmmm

**Comment by droplister** [comment]
Maybe it's to do with `getUnsyncedByAchiever` and I should set the config value to false?

**Comment by gabriel-simonetti** [comment]
Hi Dan! Could you please let me know what the issue was?

**Comment by droplister** [comment]
I'm not sure, but `'locked_sync' => false` seems to have helped.
