### ISSUE TITLE
Samples Views/Controller?

### ISSUE THREAD

**Issue by HDVinnie** [gstt/laravel-achievements#6]
Possible to add some samples that will work with this package out the box so noobs like me have a base starting point?

**Comment by gabriel-simonetti** [comment]
Working on it! Should have an example ready tomorrow.

**Comment by HDVinnie** [comment]
Awesome. Super excited for this package. Just what my wip app needs.

**Comment by HDVinnie** [comment]
any update?

**Comment by gabriel-simonetti** [comment]
Hi @HDVinnie,

I'm sorry for the late response.
I've created a CRUD app running Laravel 5 that tracks achievements for posts. Please check it out: https://github.com/gstt/laravel-achievements/example

**Comment by HDVinnie** [comment]
awesome this is great! will there be something in feature so if you reach a achievement a modal or something pops up saying 
"You've Unlocked A New Achievement" 
"Please Check Your Achievements Page For Details"

Thanks so much for this open source package

**Comment by gabriel-simonetti** [comment]
This feature is being worked on #1 and should be ready on the next RC version, due to next Sunday.

Thank you for using and suggesting features!

**Comment by gabriel-simonetti** [comment]
I've had some free time today and published RC2 today instead of Sunday!

Please check it out and let me know if you like it. :)

**Comment by HDVinnie** [comment]
I seem to be getting a error now....

composer require gstt/laravel-achievements
Using version ^0.0.3 for gstt/laravel-achievements
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize

                                                                   
  [Symfony\Component\Debug\Exception\FatalThrowableError]          
  Class 'Gstt\Achievements\AchievementsServiceProvider' not found

**Comment by gabriel-simonetti** [comment]
Make sure that you have `"gstt/laravel-achievements": "^1.0"` in the `require` section of your `composer.json`. Also, if you don't automatically download the latest version, try adding the `"minimum-stability" : "RC",` setting to the composer.json file.

For comparison, your `composer.json` file should look more or less [like this](https://github.com/gabriel-simonetti/laravel-achievements-example/blob/master/composer.json).

If you've done all that and it still shows the same error, try running `composer dump-autoload`.

**Comment by HDVinnie** [comment]
thanks....that fixed it. i figured composer update would grab latest version no matter what. I added "minimum-stability" : "RC", and "gstt/laravel-achievements": "^1.0" and is all working fine now.

Really do appreciate your time and effort
