### ISSUE TITLE
Unlocked Achievements Count (SUGGESTION)

### ISSUE THREAD

**Issue by HDVinnie** [gstt/laravel-achievements#9]
built in unlocked Achievements counter so can be easily displayed in master/default view. Maybe like so:

<?php $count = Auth::user()->unlockedAchievementsCount(); ?>

with will in return display the count of all the unlocked Achievements that user has?

**Comment by gabriel-simonetti** [comment]
The method `unlockedAchievements()` returns an instance of [`Illuminate\Database\Eloquent\Collection`](https://laravel.com/docs/5.4/eloquent-collections), so you can just use the method `count()`, as in `$achiever->unlockedAchievements()->count()`. :)

**Comment by HDVinnie** [comment]
thanks!

**Comment by watchwood** [comment]
Fyi: if all you need is a count and not the collection, it is faster for the database to do a count operation then to grab the whole list of records and then tally them up in php. Look up the operations in the eloquent query builder in the manual.

**Comment by HDVinnie** [comment]
Thought I would share here what I have done to complete this task and how I have used this package in my WIP app. Code is for the navbar trophy. Pic links of full system below. Big thanks for the 100th time to @gabriel-simonetti for this package.

```
<li class="dropdown notifications-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="livicon" data-name="trophy" data-loop="true" data-color="#f1c40f" data-hovercolor="#f1c40f" data-size="28"></i>
                  <?php $count = Auth::user()->unlockedAchievements()->count() ?>
                    <?php $achievements = Auth::user()->unlockedAchievements()->take(10) ?>
                      <span class="label label-success">{{ $count }}</span>
                </a>
                <ul class=" notifications dropdown-menu">
                  <li class="dropdown-title">Recent Achievements</li>
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <ul class="menu">
                      <li>
                        <br> @foreach($achievements as $a)
                        <p><span class="label label-primary">{{ $a->details->name }}</span> >>
                          <span class="label label-success">Unlocked</span></p>
                        @endforeach
                      </li>
                    </ul>
                  </li>
                  <li class="footer">
                    <a href="{!! route('achievements', array('username' => Auth::user()->username, 'id' => Auth::user()->id)) !!}">View All</a>
                  </li>
                </ul>
              </li>
```

http://www.ultraimg.com/image/pfeE
http://www.ultraimg.com/image/pfes
http://www.ultraimg.com/image/pfeR
